_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.502, 0.430, 0.495]
    std: [0.219, 0.229, 0.230]